-- ================================================================
-- FASE 2 — Menús y Alimentación
-- Migración: tablas menus, menu_imagenes, relaciones y políticas
-- ================================================================

-- 1. TABLA: MENUS
CREATE TABLE IF NOT EXISTS public.menus (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nombre TEXT NOT NULL,
    descripcion TEXT,
    categoria TEXT NOT NULL CHECK (
        categoria IN (
            'Desayuno',
            'Almuerzo',
            'Cena',
            'Parrilla',
            'Refrigerio',
            'Menú especial',
            'Paquetes'
        )
    ),
    precio_pp NUMERIC(12,2) NOT NULL DEFAULT 0,
    condiciones TEXT,
    imagen_url TEXT,
    activo BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Trigger de actualización para menus
DROP TRIGGER IF EXISTS set_menus_updated_at ON public.menus;
CREATE TRIGGER set_menus_updated_at
    BEFORE UPDATE ON public.menus
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- Índices de consulta rápida
CREATE INDEX IF NOT EXISTS idx_menus_categoria ON public.menus(categoria);
CREATE INDEX IF NOT EXISTS idx_menus_activo ON public.menus(activo);

-- ---------------------------------------------------------------
-- 2. TABLA: MENU_IMAGENES (Galería de fotografías por menú)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.menu_imagenes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_id UUID NOT NULL REFERENCES public.menus(id) ON DELETE CASCADE,
    url TEXT NOT NULL,
    alt TEXT,
    orden INTEGER DEFAULT 0 NOT NULL,
    es_principal BOOLEAN DEFAULT false NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_menu_imagenes_menu_id ON public.menu_imagenes(menu_id);
CREATE INDEX IF NOT EXISTS idx_menu_imagenes_orden ON public.menu_imagenes(menu_id, orden);

-- ---------------------------------------------------------------
-- 3. INTEGRACIÓN CON COTIZACIONES Y RESERVAS (Fk opcional a menus)
-- ---------------------------------------------------------------
ALTER TABLE public.cotizaciones 
    ADD COLUMN IF NOT EXISTS menu_id UUID REFERENCES public.menus(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS cantidad_alimentacion INTEGER DEFAULT 1;

ALTER TABLE public.reservas 
    ADD COLUMN IF NOT EXISTS menu_id UUID REFERENCES public.menus(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS alimentacion TEXT,
    ADD COLUMN IF NOT EXISTS costo_alimentacion NUMERIC(12,2) DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_cotizaciones_menu_id ON public.cotizaciones(menu_id);
CREATE INDEX IF NOT EXISTS idx_reservas_menu_id ON public.reservas(menu_id);

-- ---------------------------------------------------------------
-- 4. POLÍTICAS DE SEGURIDAD (RLS)
-- ---------------------------------------------------------------
ALTER TABLE public.menus ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_imagenes ENABLE ROW LEVEL SECURITY;

-- Menús: lectura pública para activos (usado por cotizador web cliente)
DROP POLICY IF EXISTS "Lectura publica de menus activos" ON public.menus;
CREATE POLICY "Lectura publica de menus activos"
    ON public.menus FOR SELECT
    TO anon, authenticated
    USING (activo = true);

-- Menús: administración total para usuarios autenticados
DROP POLICY IF EXISTS "Admin gestion total menus" ON public.menus;
CREATE POLICY "Admin gestion total menus"
    ON public.menus FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- Imágenes de menús: lectura pública
DROP POLICY IF EXISTS "Lectura publica imagenes menus" ON public.menu_imagenes;
CREATE POLICY "Lectura publica imagenes menus"
    ON public.menu_imagenes FOR SELECT
    TO anon, authenticated
    USING (true);

-- Imágenes de menús: administración total
DROP POLICY IF EXISTS "Admin gestion total imagenes menus" ON public.menu_imagenes;
CREATE POLICY "Admin gestion total imagenes menus"
    ON public.menu_imagenes FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- ---------------------------------------------------------------
-- 5. DATOS SEMILLA INICIALES (Menús campestres de ejemplo)
-- ---------------------------------------------------------------
INSERT INTO public.menus (nombre, descripcion, categoria, precio_pp, condiciones, imagen_url, activo)
VALUES
(
    'Desayuno Campestre Típico',
    'Calentao tradicional de la casa con fríjol y hogao, huevos al gusto, arepa de choclo con quesito cuajada, pan caliente, jugo de naranja recién exprimido y chocolate en jarra o café de greca.',
    'Desayuno',
    18000,
    'Servicio entre 7:30 a.m. y 10:00 a.m. Mínimo 4 personas. Incluye menaje y vajilla.',
    'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=800&q=80',
    true
),
(
    'Sancocho Tradicional de Gallina en Leña',
    'Cocido tradicional en leña de gallina criolla con plátano verde, yuca suave, papa pastusa y mazorca tierna. Acompañado de presa dorada, arroz blanco, aguacate maduro, ensalada campesina y jarra de limonada natural con panela.',
    'Almuerzo',
    35000,
    'Preparación en sitio por cocinera campesina. Mínimo 8 personas. Confirmar con 24 horas de anticipación.',
    'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80',
    true
),
(
    'Gran Parrillada Mixta Campestre',
    'Corte grueso de churrasco de res a la parrilla, pechuga marinada a las finas hierbas, chorizo santarrosano artesanal y morcilla criolla. Servido con papas saladas, arepas con mantequilla, chimichurri argentino de la casa y guacamole rústico.',
    'Parrilla',
    48000,
    'Incluye servicio de parrillero profesional durante 3 horas, carbón vegetal de leña y montaje.',
    'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
    true
),
(
    'Cena Ligera Gourmet Campestre',
    'Crema aterciopelada de calabaza y zanahoria de la huerta con croutons aromatizados, pechuga a la plancha sobre cama de vegetales salteados al wok y tostadas con finas hierbas y queso campesino.',
    'Cena',
    25000,
    'Servicio entre 6:30 p.m. y 8:30 p.m. Mínimo 4 personas.',
    'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
    true
),
(
    'Refrigerio Valluno con Empanadas Crocantes',
    'Dúo de empanadas artesanales crocantes de carne y papa con ají casero pique suave y limón, acompañado de champús valluno frío o maracuyada refrescante.',
    'Refrigerio',
    12000,
    'Ideal para la media tarde o receso de actividades. Mínimo 6 personas.',
    'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
    true
),
(
    'Costillas BBQ Ahumadas en Madera Frutal',
    'Costillar tierno de cerdo glaseado lentamente en salsa barbacoa artesanal de panela y especias, papas rústicas al romero y mazorquitas asadas a la mantequilla.',
    'Menú especial',
    42000,
    'Tiempo de preparación en sitio: 4 horas. Solicitar con 48h de anticipación.',
    'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    true
),
(
    'Paquete Pensión Completa Campestre',
    'Plan todo incluido de alimentación por persona y día: Desayuno típico campesino + Almuerzo a elección (Sancocho o Bandeja típica) + Refrigerio de la tarde + Cena completa.',
    'Paquetes',
    75000,
    'Tarifa por persona y por día completo. Aplica para toda la estancia de los huéspedes registrados.',
    'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
    true
)
ON CONFLICT DO NOTHING;
