-- =============================================================================
-- MIGRACIÓN: CAMPOS PROFESIONALES EXTENDIDOS PARA FINCAS CAMPESTRES
-- Control de Fincas Campestres
-- =============================================================================

-- 1. Añadir columnas de acomodación, políticas, precios y condiciones a la tabla fincas
ALTER TABLE public.fincas 
  ADD COLUMN IF NOT EXISTS habitaciones INTEGER DEFAULT 3,
  ADD COLUMN IF NOT EXISTS camas INTEGER DEFAULT 5,
  ADD COLUMN IF NOT EXISTS banos INTEGER DEFAULT 2,
  ADD COLUMN IF NOT EXISTS checkin_hora TEXT DEFAULT '15:00',
  ADD COLUMN IF NOT EXISTS checkout_hora TEXT DEFAULT '13:00',
  ADD COLUMN IF NOT EXISTS politica_mascotas TEXT DEFAULT 'permitido',
  ADD COLUMN IF NOT EXISTS politica_musica TEXT DEFAULT 'moderada',
  ADD COLUMN IF NOT EXISTS precio_finca_completa NUMERIC(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS deposito_garantia NUMERIC(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS normas TEXT,
  ADD COLUMN IF NOT EXISTS indicaciones_llegada TEXT;

-- 2. Asegurar que la tabla finca_amenidades tenga índices y políticas adecuadas
CREATE TABLE IF NOT EXISTS public.finca_amenidades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finca_id UUID NOT NULL REFERENCES public.fincas(id) ON DELETE CASCADE,
    nombre TEXT NOT NULL,
    icono TEXT DEFAULT 'check'
);

CREATE INDEX IF NOT EXISTS idx_finca_amenidades_finca_id ON public.finca_amenidades(finca_id);

-- Habilitar RLS en finca_amenidades si no está habilitado
ALTER TABLE public.finca_amenidades ENABLE ROW LEVEL SECURITY;

-- Políticas de lectura pública y escritura administrativa para finca_amenidades
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'finca_amenidades' AND policyname = 'Lectura pública de amenidades'
  ) THEN
    CREATE POLICY "Lectura pública de amenidades"
      ON public.finca_amenidades FOR SELECT
      TO anon, authenticated
      USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'finca_amenidades' AND policyname = 'Admin gestión total amenidades'
  ) THEN
    CREATE POLICY "Admin gestión total amenidades"
      ON public.finca_amenidades FOR ALL
      TO anon, authenticated
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;
