-- ==============================================================================
-- SCRIPT MAESTRO DE MIGRACIÓN Y PERSISTENCIA COMPLETA
-- Proyecto: Control de Fincas Campestres
-- Ejecutar en: Supabase SQL Editor (1 solo clic, completamente idempotente)
-- ==============================================================================

-- 0. EXTENSIONES Y FUNCIONES BASE
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ==============================================================================
-- 1. BUCKET DE ALMACENAMIENTO (STORAGE) Y POLÍTICAS PÚBLICAS
-- Soporta: fotos de fincas, fotos de menús y documentos PDF (Separación, Abonos, etc.)
-- ==============================================================================

DO $$
BEGIN
    -- Asegurar que el bucket exista y sea público
    BEGIN
        INSERT INTO storage.buckets (id, name, public)
        VALUES ('finca-imagenes', 'finca-imagenes', true)
        ON CONFLICT (id) DO UPDATE SET public = true;
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'Aviso al registrar bucket finca-imagenes: %', SQLERRM;
    END;

    -- Políticas de acceso para storage.objects en el bucket 'finca-imagenes'
    BEGIN
        DROP POLICY IF EXISTS "Acceso publico lectura finca-imagenes" ON storage.objects;
        CREATE POLICY "Acceso publico lectura finca-imagenes"
            ON storage.objects FOR SELECT
            TO anon, authenticated
            USING (bucket_id = 'finca-imagenes');
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'Aviso politica SELECT storage.objects: %', SQLERRM;
    END;

    BEGIN
        DROP POLICY IF EXISTS "Insercion total finca-imagenes" ON storage.objects;
        CREATE POLICY "Insercion total finca-imagenes"
            ON storage.objects FOR INSERT
            TO anon, authenticated
            WITH CHECK (bucket_id = 'finca-imagenes');
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'Aviso politica INSERT storage.objects: %', SQLERRM;
    END;

    BEGIN
        DROP POLICY IF EXISTS "Actualizacion total finca-imagenes" ON storage.objects;
        CREATE POLICY "Actualizacion total finca-imagenes"
            ON storage.objects FOR UPDATE
            TO anon, authenticated
            USING (bucket_id = 'finca-imagenes')
            WITH CHECK (bucket_id = 'finca-imagenes');
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'Aviso politica UPDATE storage.objects: %', SQLERRM;
    END;

    BEGIN
        DROP POLICY IF EXISTS "Eliminacion total finca-imagenes" ON storage.objects;
        CREATE POLICY "Eliminacion total finca-imagenes"
            ON storage.objects FOR DELETE
            TO anon, authenticated
            USING (bucket_id = 'finca-imagenes');
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'Aviso politica DELETE storage.objects: %', SQLERRM;
    END;
END $$;

-- ==============================================================================
-- 2. TABLAS BASE: FINCAS, IMÁGENES, AMENIDADES Y PLANES
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.fincas (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nombre TEXT NOT NULL,
    zona TEXT DEFAULT 'Santa Elena, Valle',
    capacidad INTEGER NOT NULL DEFAULT 10,
    precio_pp NUMERIC(12,2) NOT NULL DEFAULT 0,
    descripcion TEXT,
    estado TEXT NOT NULL DEFAULT 'disponible' CHECK (estado IN ('disponible', 'alta_demanda', 'fin_de_semana', 'no_disponible')),
    whatsapp TEXT,
    activo BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Asegurar columnas en fincas
ALTER TABLE public.fincas ADD COLUMN IF NOT EXISTS zona TEXT DEFAULT 'Santa Elena, Valle';
ALTER TABLE public.fincas ADD COLUMN IF NOT EXISTS whatsapp TEXT;
ALTER TABLE public.fincas ADD COLUMN IF NOT EXISTS activo BOOLEAN NOT NULL DEFAULT true;

DROP TRIGGER IF EXISTS set_fincas_updated_at ON public.fincas;
CREATE TRIGGER set_fincas_updated_at
    BEFORE UPDATE ON public.fincas
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- FINCA_IMAGENES
CREATE TABLE IF NOT EXISTS public.finca_imagenes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finca_id UUID NOT NULL REFERENCES public.fincas(id) ON DELETE CASCADE,
    url TEXT NOT NULL,
    alt TEXT,
    orden INTEGER DEFAULT 0 NOT NULL,
    es_principal BOOLEAN DEFAULT false NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_finca_imagenes_finca_id ON public.finca_imagenes(finca_id);
CREATE INDEX IF NOT EXISTS idx_finca_imagenes_orden ON public.finca_imagenes(finca_id, orden);

-- FINCA_AMENIDADES
CREATE TABLE IF NOT EXISTS public.finca_amenidades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finca_id UUID NOT NULL REFERENCES public.fincas(id) ON DELETE CASCADE,
    nombre TEXT NOT NULL,
    icono TEXT DEFAULT 'check'
);

CREATE INDEX IF NOT EXISTS idx_finca_amenidades_finca_id ON public.finca_amenidades(finca_id);

-- FINCA_PLANES
CREATE TABLE IF NOT EXISTS public.finca_planes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finca_id UUID NOT NULL REFERENCES public.fincas(id) ON DELETE CASCADE,
    nombre TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_finca_planes_finca_id ON public.finca_planes(finca_id);

-- ==============================================================================
-- 3. MENÚS Y GASTRONOMÍA
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.menus (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nombre TEXT NOT NULL,
    descripcion TEXT,
    categoria TEXT NOT NULL CHECK (
        categoria IN (
            'Desayuno',
            'Almuerzo',
            'Cena',
            'Parrilla',
            'Refrigerio',
            'Menú especial',
            'Paquetes'
        )
    ),
    precio_pp NUMERIC(12,2) NOT NULL DEFAULT 0,
    condiciones TEXT,
    imagen_url TEXT,
    activo BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

DROP TRIGGER IF EXISTS set_menus_updated_at ON public.menus;
CREATE TRIGGER set_menus_updated_at
    BEFORE UPDATE ON public.menus
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

CREATE INDEX IF NOT EXISTS idx_menus_categoria ON public.menus(categoria);
CREATE INDEX IF NOT EXISTS idx_menus_activo ON public.menus(activo);

-- MENU_IMAGENES
CREATE TABLE IF NOT EXISTS public.menu_imagenes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_id UUID NOT NULL REFERENCES public.menus(id) ON DELETE CASCADE,
    url TEXT NOT NULL,
    alt TEXT,
    orden INTEGER DEFAULT 0 NOT NULL,
    es_principal BOOLEAN DEFAULT false NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_menu_imagenes_menu_id ON public.menu_imagenes(menu_id);
CREATE INDEX IF NOT EXISTS idx_menu_imagenes_orden ON public.menu_imagenes(menu_id, orden);

-- ==============================================================================
-- 4. CLIENTES
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.clientes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nombre TEXT NOT NULL,
    apellido TEXT,
    telefono TEXT,
    whatsapp TEXT,
    correo TEXT,
    observaciones TEXT,
    activo BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.clientes ADD COLUMN IF NOT EXISTS observaciones TEXT;
ALTER TABLE public.clientes ADD COLUMN IF NOT EXISTS activo BOOLEAN NOT NULL DEFAULT true;

DROP TRIGGER IF EXISTS set_clientes_updated_at ON public.clientes;
CREATE TRIGGER set_clientes_updated_at
    BEFORE UPDATE ON public.clientes
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

CREATE INDEX IF NOT EXISTS idx_clientes_whatsapp ON public.clientes(whatsapp);

-- ==============================================================================
-- 5. COTIZACIONES Y RESERVAS (CON INTEGRIDAD HISTÓRICA ON DELETE SET NULL)
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.cotizaciones (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    consecutivo TEXT,
    cliente_id UUID REFERENCES public.clientes(id) ON DELETE SET NULL,
    finca_id UUID REFERENCES public.fincas(id) ON DELETE SET NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    personas INTEGER NOT NULL DEFAULT 1,
    alimentacion TEXT DEFAULT 'Sin alimentacion',
    menu_id UUID REFERENCES public.menus(id) ON DELETE SET NULL,
    cantidad_alimentacion INTEGER DEFAULT 1,
    subtotal_alojamiento NUMERIC(12,2) NOT NULL DEFAULT 0,
    costo_alimentacion NUMERIC(12,2) NOT NULL DEFAULT 0,
    descuento NUMERIC(12,2) NOT NULL DEFAULT 0,
    recargo NUMERIC(12,2) NOT NULL DEFAULT 0,
    total NUMERIC(12,2) NOT NULL DEFAULT 0,
    estado TEXT NOT NULL DEFAULT 'borrador'
        CHECK (estado IN ('borrador','cotizada','enviada','pendiente','confirmada','cancelada','vencida')),
    notas TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.cotizaciones ADD COLUMN IF NOT EXISTS consecutivo TEXT;
ALTER TABLE public.cotizaciones ADD COLUMN IF NOT EXISTS menu_id UUID REFERENCES public.menus(id) ON DELETE SET NULL;
ALTER TABLE public.cotizaciones ADD COLUMN IF NOT EXISTS cantidad_alimentacion INTEGER DEFAULT 1;

-- Asegurar que finca_id y cliente_id permitan NULL para preservación histórica
ALTER TABLE public.cotizaciones ALTER COLUMN finca_id DROP NOT NULL;
ALTER TABLE public.cotizaciones DROP CONSTRAINT IF EXISTS cotizaciones_finca_id_fkey;
ALTER TABLE public.cotizaciones 
    ADD CONSTRAINT cotizaciones_finca_id_fkey 
    FOREIGN KEY (finca_id) REFERENCES public.fincas(id) ON DELETE SET NULL;

ALTER TABLE public.cotizaciones DROP CONSTRAINT IF EXISTS cotizaciones_cliente_id_fkey;
ALTER TABLE public.cotizaciones 
    ADD CONSTRAINT cotizaciones_cliente_id_fkey 
    FOREIGN KEY (cliente_id) REFERENCES public.clientes(id) ON DELETE SET NULL;

DROP TRIGGER IF EXISTS set_cotizaciones_updated_at ON public.cotizaciones;
CREATE TRIGGER set_cotizaciones_updated_at
    BEFORE UPDATE ON public.cotizaciones
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

CREATE INDEX IF NOT EXISTS idx_cotizaciones_consecutivo ON public.cotizaciones(consecutivo);
CREATE INDEX IF NOT EXISTS idx_cotizaciones_cliente ON public.cotizaciones(cliente_id);
CREATE INDEX IF NOT EXISTS idx_cotizaciones_finca ON public.cotizaciones(finca_id);
CREATE INDEX IF NOT EXISTS idx_cotizaciones_estado ON public.cotizaciones(estado);

-- RESERVAS
CREATE TABLE IF NOT EXISTS public.reservas (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    consecutivo TEXT,
    cotizacion_id UUID REFERENCES public.cotizaciones(id) ON DELETE SET NULL,
    cliente_id UUID REFERENCES public.clientes(id) ON DELETE SET NULL,
    finca_id UUID REFERENCES public.fincas(id) ON DELETE SET NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    personas INTEGER NOT NULL DEFAULT 1,
    valor_total NUMERIC(12,2) NOT NULL DEFAULT 0,
    separacion NUMERIC(12,2) NOT NULL DEFAULT 0,
    estado TEXT NOT NULL DEFAULT 'activa'
        CHECK (estado IN ('activa','completada','cancelada','no_show')),
    observaciones TEXT,
    cliente_snapshot JSONB,
    finca_snapshot JSONB,
    cotizacion_snapshot JSONB,
    fecha_cierre TIMESTAMPTZ,
    cerrada_por TEXT,
    notas_cierre TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.reservas ADD COLUMN IF NOT EXISTS consecutivo TEXT;
ALTER TABLE public.reservas ADD COLUMN IF NOT EXISTS cliente_snapshot JSONB;
ALTER TABLE public.reservas ADD COLUMN IF NOT EXISTS finca_snapshot JSONB;
ALTER TABLE public.reservas ADD COLUMN IF NOT EXISTS cotizacion_snapshot JSONB;
ALTER TABLE public.reservas ADD COLUMN IF NOT EXISTS fecha_cierre TIMESTAMPTZ;
ALTER TABLE public.reservas ADD COLUMN IF NOT EXISTS cerrada_por TEXT;
ALTER TABLE public.reservas ADD COLUMN IF NOT EXISTS notas_cierre TEXT;

-- Permitir que las reservas mantengan su snapshot aunque la finca se elimine
ALTER TABLE public.reservas ALTER COLUMN finca_id DROP NOT NULL;
ALTER TABLE public.reservas DROP CONSTRAINT IF EXISTS reservas_finca_id_fkey;
ALTER TABLE public.reservas 
    ADD CONSTRAINT reservas_finca_id_fkey 
    FOREIGN KEY (finca_id) REFERENCES public.fincas(id) ON DELETE SET NULL;

ALTER TABLE public.reservas DROP CONSTRAINT IF EXISTS reservas_cliente_id_fkey;
ALTER TABLE public.reservas 
    ADD CONSTRAINT reservas_cliente_id_fkey 
    FOREIGN KEY (cliente_id) REFERENCES public.clientes(id) ON DELETE SET NULL;

DROP TRIGGER IF EXISTS set_reservas_updated_at ON public.reservas;
CREATE TRIGGER set_reservas_updated_at
    BEFORE UPDATE ON public.reservas
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

CREATE INDEX IF NOT EXISTS idx_reservas_consecutivo ON public.reservas(consecutivo);
CREATE INDEX IF NOT EXISTS idx_reservas_cliente ON public.reservas(cliente_id);
CREATE INDEX IF NOT EXISTS idx_reservas_finca ON public.reservas(finca_id);
CREATE INDEX IF NOT EXISTS idx_reservas_estado ON public.reservas(estado);

-- Trigger de preservación automática de snapshots en reservas
CREATE OR REPLACE FUNCTION public.fn_preservar_snapshot_reserva()
RETURNS TRIGGER AS $$
DECLARE
    v_cliente RECORD;
    v_finca RECORD;
    v_cotizacion RECORD;
BEGIN
    IF NEW.cliente_snapshot IS NULL AND NEW.cliente_id IS NOT NULL THEN
        SELECT id, nombre, apellido, whatsapp, telefono, correo
        INTO v_cliente
        FROM public.clientes
        WHERE id = NEW.cliente_id;

        IF FOUND THEN
            NEW.cliente_snapshot := jsonb_build_object(
                'id', v_cliente.id,
                'nombre', v_cliente.nombre,
                'apellido', v_cliente.apellido,
                'whatsapp', v_cliente.whatsapp,
                'telefono', v_cliente.telefono,
                'correo', v_cliente.correo
            );
        END IF;
    END IF;

    IF NEW.finca_snapshot IS NULL AND NEW.finca_id IS NOT NULL THEN
        SELECT id, nombre, zona, capacidad, precio_pp
        INTO v_finca
        FROM public.fincas
        WHERE id = NEW.finca_id;

        IF FOUND THEN
            NEW.finca_snapshot := jsonb_build_object(
                'id', v_finca.id,
                'nombre', v_finca.nombre,
                'zona', v_finca.zona,
                'capacidad', v_finca.capacidad,
                'precio_pp', v_finca.precio_pp
            );
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_preservar_snapshot_reserva ON public.reservas;
CREATE TRIGGER trg_preservar_snapshot_reserva
    BEFORE INSERT OR UPDATE ON public.reservas
    FOR EACH ROW
    EXECUTE FUNCTION public.fn_preservar_snapshot_reserva();

-- ==============================================================================
-- 6. TABLA DISPONIBILIDAD (CON ENLACE A RESERVA_ID)
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.disponibilidad (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finca_id UUID NOT NULL REFERENCES public.fincas(id) ON DELETE CASCADE,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    estado TEXT NOT NULL DEFAULT 'ocupado',
    personas INTEGER,
    notas TEXT,
    reserva_id UUID REFERENCES public.reservas(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT check_fechas CHECK (fecha_fin >= fecha_inicio)
);

ALTER TABLE public.disponibilidad ADD COLUMN IF NOT EXISTS reserva_id UUID REFERENCES public.reservas(id) ON DELETE CASCADE;
ALTER TABLE public.disponibilidad DROP CONSTRAINT IF EXISTS disponibilidad_estado_check;
ALTER TABLE public.disponibilidad 
    ADD CONSTRAINT disponibilidad_estado_check 
    CHECK (estado IN ('ocupado', 'libre', 'bloqueado'));

CREATE INDEX IF NOT EXISTS idx_disponibilidad_finca_fechas 
    ON public.disponibilidad(finca_id, fecha_inicio, fecha_fin);
CREATE INDEX IF NOT EXISTS idx_disponibilidad_reserva_id 
    ON public.disponibilidad(reserva_id);

-- ==============================================================================
-- 7. TABLA PAGOS
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.pagos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    reserva_id UUID NOT NULL REFERENCES public.reservas(id) ON DELETE CASCADE,
    tipo TEXT NOT NULL DEFAULT 'abono',
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    valor NUMERIC(12,2) NOT NULL DEFAULT 0,
    metodo TEXT DEFAULT 'transferencia',
    comprobante_url TEXT,
    observacion TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.pagos DROP CONSTRAINT IF EXISTS pagos_tipo_check;
ALTER TABLE public.pagos
    ADD CONSTRAINT pagos_tipo_check
    CHECK (tipo IN ('separacion', 'abono', 'pago_total', 'liquidacion', 'devolucion'));

CREATE INDEX IF NOT EXISTS idx_pagos_reserva ON public.pagos(reserva_id);

-- ==============================================================================
-- 8. COMUNICACIONES Y CIERRES DE RESERVA
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.comunicaciones (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    cliente_id UUID REFERENCES public.clientes(id) ON DELETE SET NULL,
    reserva_id UUID REFERENCES public.reservas(id) ON DELETE SET NULL,
    cotizacion_id UUID REFERENCES public.cotizaciones(id) ON DELETE SET NULL,
    tipo TEXT NOT NULL DEFAULT 'general',
    destinatario TEXT,
    telefono TEXT,
    mensaje TEXT NOT NULL,
    estado TEXT NOT NULL DEFAULT 'enviado',
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_comunicaciones_cliente ON public.comunicaciones(cliente_id);
CREATE INDEX IF NOT EXISTS idx_comunicaciones_reserva ON public.comunicaciones(reserva_id);

CREATE TABLE IF NOT EXISTS public.cierres_reservas (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    reserva_id UUID NOT NULL REFERENCES public.reservas(id) ON DELETE CASCADE,
    fecha_cierre TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    responsable TEXT DEFAULT 'Administrador',
    estado_cierre TEXT NOT NULL DEFAULT 'completada'
        CHECK (estado_cierre IN ('completada', 'cancelada', 'no_show')),
    calificacion INTEGER CHECK (calificacion BETWEEN 1 AND 5),
    estado_entrega_finca TEXT DEFAULT 'excelente'
        CHECK (estado_entrega_finca IN ('excelente', 'bueno', 'con_observaciones', 'danos_reportados')),
    deposito_garantia_devuelto BOOLEAN DEFAULT true,
    valor_deposito_devuelto NUMERIC(12,2) DEFAULT 0,
    notas_cierre TEXT,
    observaciones_entrega TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT uq_cierre_reserva UNIQUE (reserva_id)
);

CREATE INDEX IF NOT EXISTS idx_cierres_reserva_id ON public.cierres_reservas(reserva_id);

-- ==============================================================================
-- 9. CONFIGURACIÓN GENERAL Y CONTENIDO DEL SITIO
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.configuracion_general (
    id TEXT PRIMARY KEY DEFAULT 'general',
    nombre_empresa TEXT NOT NULL DEFAULT 'Control de Fincas Campestres',
    nit TEXT DEFAULT '900.123.456-7',
    eslogan TEXT DEFAULT 'Experiencias exclusivas y descanso en la naturaleza',
    logo_url TEXT,
    telefono TEXT DEFAULT '+57 317 682 7093',
    whatsapp TEXT NOT NULL DEFAULT '573176827093',
    correo TEXT DEFAULT 'reservas@fincascampestres.com',
    direccion TEXT DEFAULT 'Santa Elena, El Cerrito, Valle del Cauca',
    ciudad TEXT DEFAULT 'Valle del Cauca, Colombia',
    sitio_web TEXT DEFAULT 'https://fincascampestres.com',
    redes_sociales JSONB DEFAULT '{"facebook": "https://facebook.com", "instagram": "https://instagram.com", "tiktok": "https://tiktok.com"}'::jsonb,
    doc_logo_url TEXT,
    doc_encabezado TEXT DEFAULT 'CONTROL DE FINCAS CAMPESTRES — ALQUILER Y SERVICIOS TURÍSTICOS',
    doc_pie_pagina TEXT DEFAULT 'Control de Fincas Campestres • Documento oficial generado automáticamente • Santa Elena, Valle del Cauca',
    doc_contacto_info TEXT DEFAULT 'WhatsApp: +57 317 682 7093 | reservas@fincascampestres.com | Santa Elena, Valle',
    terminos_condiciones TEXT DEFAULT '• La separación garantiza la reserva y bloquea la disponibilidad para las fechas pactadas.
• El saldo pendiente debe cancelarse en su totalidad antes del ingreso a la finca.
• En caso de cancelación por el cliente, el anticipo no será reembolsable salvo acuerdo formal previo.
• El huésped es responsable del cuidado del inmueble, enseres e inventario entregados.
• La capacidad máxima de personas pactada en este documento debe respetarse estrictamente.',
    textos_legales TEXT DEFAULT 'Documento expedido de conformidad con las disposiciones turísticas y comerciales colombianas vigentes. Válido como soporte contractual de reserva de finca campestre y servicios complementarios.',
    politicas_cancelacion TEXT DEFAULT 'Cancelaciones con más de 15 días calendario de anticipación permiten reprogramación sujeta a disponibilidad dentro del mismo año. Cancelaciones posteriores conllevan la pérdida de la suma de separación.',
    prefijo_cotizacion TEXT NOT NULL DEFAULT '',
    siguiente_cotizacion INTEGER NOT NULL DEFAULT 1001,
    prefijo_separacion TEXT NOT NULL DEFAULT '',
    siguiente_separacion INTEGER NOT NULL DEFAULT 1001,
    prefijo_abono TEXT NOT NULL DEFAULT '',
    siguiente_abono INTEGER NOT NULL DEFAULT 1001,
    prefijo_estado_cuenta TEXT NOT NULL DEFAULT '',
    siguiente_estado_cuenta INTEGER NOT NULL DEFAULT 1001,
    prefijo_paz_salvo TEXT NOT NULL DEFAULT '',
    siguiente_paz_salvo INTEGER NOT NULL DEFAULT 1001,
    prefijo_propuesta_menu TEXT NOT NULL DEFAULT '',
    siguiente_propuesta_menu INTEGER NOT NULL DEFAULT 1001,
    banco_nombre TEXT DEFAULT 'Bancolombia',
    banco_tipo_cuenta TEXT DEFAULT 'Ahorros',
    banco_cuenta TEXT DEFAULT '',
    banco_titular TEXT DEFAULT 'Control de Fincas Campestres',
    plantillas_comunicacion JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.configuracion_general ADD COLUMN IF NOT EXISTS plantillas_comunicacion JSONB DEFAULT '{}'::jsonb;
ALTER TABLE public.configuracion_general ADD COLUMN IF NOT EXISTS prefijo_cotizacion TEXT NOT NULL DEFAULT '';
ALTER TABLE public.configuracion_general ADD COLUMN IF NOT EXISTS siguiente_cotizacion INTEGER NOT NULL DEFAULT 1001;
ALTER TABLE public.configuracion_general ADD COLUMN IF NOT EXISTS prefijo_separacion TEXT NOT NULL DEFAULT '';
ALTER TABLE public.configuracion_general ADD COLUMN IF NOT EXISTS siguiente_separacion INTEGER NOT NULL DEFAULT 1001;

INSERT INTO public.configuracion_general (id) 
VALUES ('general') 
ON CONFLICT (id) DO UPDATE SET updated_at = now();

-- CONTENIDO_SITIO
CREATE TABLE IF NOT EXISTS public.contenido_sitio (
    id TEXT PRIMARY KEY DEFAULT 'principal',
    orden_secciones JSONB NOT NULL DEFAULT '["banner", "hero", "destacados", "estado", "filtros", "catalogo", "menus", "faq"]'::jsonb,
    banner_visible BOOLEAN NOT NULL DEFAULT true,
    banner_texto TEXT NOT NULL DEFAULT '🌿 ¡Reserva directa sin comisiones! Consulta fechas libres en nuestro calendario y cotiza al instante por WhatsApp.',
    banner_link_texto TEXT DEFAULT 'Ver disponibilidad',
    banner_link_url TEXT DEFAULT '#catalogo',
    banner_tipo TEXT NOT NULL DEFAULT 'promo',
    hero_visible BOOLEAN NOT NULL DEFAULT true,
    hero_eyebrow TEXT NOT NULL DEFAULT 'Reserva directa sin comisiones',
    hero_titulo TEXT NOT NULL DEFAULT 'Tu escapada campestre empieza aquí',
    hero_subtitulo TEXT NOT NULL DEFAULT 'Elige la finca ideal en Santa Elena, consulta la disponibilidad en tiempo real en nuestro calendario y cotiza tu reserva instantáneamente por WhatsApp.',
    hero_cta_texto TEXT NOT NULL DEFAULT 'Explorar fincas disponibles',
    hero_cta_secundario_texto TEXT DEFAULT 'Conocer gastronomía',
    hero_mostrar_metricas BOOLEAN NOT NULL DEFAULT true,
    hero_mostrar_pasos BOOLEAN NOT NULL DEFAULT true,
    hero_paso_1 TEXT NOT NULL DEFAULT 'Elige tus fechas',
    hero_paso_2 TEXT NOT NULL DEFAULT 'Consulta el calendario',
    hero_paso_3 TEXT NOT NULL DEFAULT 'Cotiza por WhatsApp',
    hero_imagen_url TEXT,
    hero_badge_ubicacion TEXT DEFAULT 'Santa Elena, El Cerrito, Valle',
    destacados_visible BOOLEAN NOT NULL DEFAULT true,
    destacados_titulo TEXT NOT NULL DEFAULT '¿Por qué reservar con nosotros?',
    destacados_subtitulo TEXT NOT NULL DEFAULT 'Garantizamos tranquilidad, transparencia y el mejor descanso en el Valle del Cauca',
    destacados_items JSONB,
    estado_visible BOOLEAN NOT NULL DEFAULT true,
    estado_titulo TEXT NOT NULL DEFAULT 'Ocupación de Fincas en Tiempo Real',
    estado_subtitulo TEXT NOT NULL DEFAULT 'Revisa la ocupación actual para planear tu descanso',
    menus_visible BOOLEAN NOT NULL DEFAULT true,
    menus_titulo TEXT NOT NULL DEFAULT 'Planes de Alimentación & Menús Campestres',
    menus_subtitulo TEXT NOT NULL DEFAULT 'Complementa tu estadía con gastronomía casera de la más alta calidad',
    faq_visible BOOLEAN NOT NULL DEFAULT true,
    faq_titulo TEXT NOT NULL DEFAULT 'Preguntas Frecuentes',
    faq_subtitulo TEXT NOT NULL DEFAULT 'Todo lo que necesitas saber antes de reservar tu estadía',
    faq_items JSONB,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

INSERT INTO public.contenido_sitio (id) 
VALUES ('principal') 
ON CONFLICT (id) DO NOTHING;

-- ==============================================================================
-- 10. FUNCIONES RPC DE CONSECUTIVOS ATÓMICOS CONCURRENTES (1001+)
-- ==============================================================================

CREATE OR REPLACE FUNCTION public.siguiente_consecutivo_cotizacion()
RETURNS TEXT AS $$
DECLARE
  v_numero INTEGER;
BEGIN
  SELECT GREATEST(1001, COALESCE(siguiente_cotizacion, 1001))
  INTO v_numero
  FROM public.configuracion_general
  WHERE id = 'general'
  FOR UPDATE;

  IF NOT FOUND THEN
    INSERT INTO public.configuracion_general (id, prefijo_cotizacion, siguiente_cotizacion)
    VALUES ('general', '', 1002);
    RETURN '1001';
  END IF;

  UPDATE public.configuracion_general
  SET siguiente_cotizacion = v_numero + 1
  WHERE id = 'general';

  RETURN v_numero::TEXT;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.siguiente_consecutivo_reserva()
RETURNS TEXT AS $$
DECLARE
  v_numero INTEGER;
BEGIN
  SELECT GREATEST(1001, COALESCE(siguiente_separacion, 1001))
  INTO v_numero
  FROM public.configuracion_general
  WHERE id = 'general'
  FOR UPDATE;

  IF NOT FOUND THEN
    INSERT INTO public.configuracion_general (id, prefijo_separacion, siguiente_separacion)
    VALUES ('general', '', 1002);
    RETURN '1001';
  END IF;

  UPDATE public.configuracion_general
  SET siguiente_separacion = v_numero + 1
  WHERE id = 'general';

  RETURN v_numero::TEXT;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION public.siguiente_consecutivo_cotizacion() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.siguiente_consecutivo_reserva() TO anon, authenticated;

-- ==============================================================================
-- 11. HABILITAR ROW LEVEL SECURITY (RLS) EN TODAS LAS TABLAS
-- ==============================================================================

ALTER TABLE public.fincas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.finca_imagenes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.finca_planes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.finca_amenidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.disponibilidad ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cotizaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reservas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pagos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comunicaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cierres_reservas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.configuracion_general ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contenido_sitio ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menus ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_imagenes ENABLE ROW LEVEL SECURITY;

-- ==============================================================================
-- 12. POLÍTICAS COMPLETAS DE LECTURA Y ESCRITURA (ANON + AUTHENTICATED)
-- Garantizan funcionamiento fluido sin bloqueos de permisos
-- ==============================================================================

-- FINCAS Y FOTOS
DROP POLICY IF EXISTS "Acceso total fincas anon y auth" ON public.fincas;
CREATE POLICY "Acceso total fincas anon y auth" ON public.fincas FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Acceso total finca_imagenes anon y auth" ON public.finca_imagenes;
CREATE POLICY "Acceso total finca_imagenes anon y auth" ON public.finca_imagenes FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Acceso total finca_planes anon y auth" ON public.finca_planes;
CREATE POLICY "Acceso total finca_planes anon y auth" ON public.finca_planes FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Acceso total finca_amenidades anon y auth" ON public.finca_amenidades;
CREATE POLICY "Acceso total finca_amenidades anon y auth" ON public.finca_amenidades FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- MENÚS Y FOTOS
DROP POLICY IF EXISTS "Acceso total menus anon y auth" ON public.menus;
CREATE POLICY "Acceso total menus anon y auth" ON public.menus FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Acceso total menu_imagenes anon y auth" ON public.menu_imagenes;
CREATE POLICY "Acceso total menu_imagenes anon y auth" ON public.menu_imagenes FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- DISPONIBILIDAD
DROP POLICY IF EXISTS "Acceso total disponibilidad anon y auth" ON public.disponibilidad;
CREATE POLICY "Acceso total disponibilidad anon y auth" ON public.disponibilidad FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- CLIENTES
DROP POLICY IF EXISTS "Acceso total clientes anon y auth" ON public.clientes;
CREATE POLICY "Acceso total clientes anon y auth" ON public.clientes FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- COTIZACIONES
DROP POLICY IF EXISTS "Acceso total cotizaciones anon y auth" ON public.cotizaciones;
CREATE POLICY "Acceso total cotizaciones anon y auth" ON public.cotizaciones FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- RESERVAS
DROP POLICY IF EXISTS "Acceso total reservas anon y auth" ON public.reservas;
CREATE POLICY "Acceso total reservas anon y auth" ON public.reservas FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- PAGOS
DROP POLICY IF EXISTS "Acceso total pagos anon y auth" ON public.pagos;
CREATE POLICY "Acceso total pagos anon y auth" ON public.pagos FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- COMUNICACIONES
DROP POLICY IF EXISTS "Acceso total comunicaciones anon y auth" ON public.comunicaciones;
CREATE POLICY "Acceso total comunicaciones anon y auth" ON public.comunicaciones FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- CIERRES_RESERVAS
DROP POLICY IF EXISTS "Acceso total cierres_reservas anon y auth" ON public.cierres_reservas;
CREATE POLICY "Acceso total cierres_reservas anon y auth" ON public.cierres_reservas FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- CONFIGURACIÓN GENERAL Y CONTENIDO SITIO
DROP POLICY IF EXISTS "Acceso total configuracion anon y auth" ON public.configuracion_general;
CREATE POLICY "Acceso total configuracion anon y auth" ON public.configuracion_general FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Acceso total contenido anon y auth" ON public.contenido_sitio;
CREATE POLICY "Acceso total contenido anon y auth" ON public.contenido_sitio FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ==============================================================================
-- 13. REPLICACIÓN SUPABASE REALTIME
-- ==============================================================================

DO $$
BEGIN
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.fincas;
    EXCEPTION WHEN duplicate_object THEN END;
    
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.disponibilidad;
    EXCEPTION WHEN duplicate_object THEN END;
    
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.reservas;
    EXCEPTION WHEN duplicate_object THEN END;
    
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.cotizaciones;
    EXCEPTION WHEN duplicate_object THEN END;
    
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.clientes;
    EXCEPTION WHEN duplicate_object THEN END;
    
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.comunicaciones;
    EXCEPTION WHEN duplicate_object THEN END;
    
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.contenido_sitio;
    EXCEPTION WHEN duplicate_object THEN END;
    
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.configuracion_general;
    EXCEPTION WHEN duplicate_object THEN END;
    
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.menus;
    EXCEPTION WHEN duplicate_object THEN END;
END $$;

-- ==============================================================================
-- 14. RECARGA DEL ESQUEMA POSTGREST (APIs y caché instantáneo)
-- ==============================================================================

NOTIFY pgrst, 'reload schema';
