-- ================================================================
-- ESQUEMA COMPLETO: CONTROL DE FINCAS CAMPESTRES DE ALQUILER
-- Base de datos: PostgreSQL en Supabase
-- ================================================================

-- 1. EXTENSIONES
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. TABLA: FINCAS
CREATE TABLE IF NOT EXISTS public.fincas (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nombre TEXT NOT NULL,
    zona TEXT DEFAULT 'Santa Elena, Valle',
    capacidad INTEGER NOT NULL DEFAULT 10,
    precio_pp NUMERIC(12,2) NOT NULL DEFAULT 0,
    descripcion TEXT,
    estado TEXT NOT NULL DEFAULT 'disponible' CHECK (estado IN ('disponible', 'alta_demanda', 'fin_de_semana', 'no_disponible')),
    whatsapp TEXT,
    activo BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Trigger para updated_at en fincas
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_fincas_updated_at ON public.fincas;
CREATE TRIGGER set_fincas_updated_at
    BEFORE UPDATE ON public.fincas
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- 3. TABLA: FINCA_IMAGENES
CREATE TABLE IF NOT EXISTS public.finca_imagenes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finca_id UUID NOT NULL REFERENCES public.fincas(id) ON DELETE CASCADE,
    url TEXT NOT NULL,
    alt TEXT,
    orden INTEGER DEFAULT 0 NOT NULL,
    es_principal BOOLEAN DEFAULT false NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_finca_imagenes_finca_id ON public.finca_imagenes(finca_id);
CREATE INDEX IF NOT EXISTS idx_finca_imagenes_orden ON public.finca_imagenes(finca_id, orden);

-- 4. TABLA: FINCA_AMENIDADES
CREATE TABLE IF NOT EXISTS public.finca_amenidades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finca_id UUID NOT NULL REFERENCES public.fincas(id) ON DELETE CASCADE,
    nombre TEXT NOT NULL,
    icono TEXT DEFAULT 'check'
);

CREATE INDEX IF NOT EXISTS idx_finca_amenidades_finca_id ON public.finca_amenidades(finca_id);

-- 5. TABLA: FINCA_PLANES
CREATE TABLE IF NOT EXISTS public.finca_planes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finca_id UUID NOT NULL REFERENCES public.fincas(id) ON DELETE CASCADE,
    nombre TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_finca_planes_finca_id ON public.finca_planes(finca_id);

-- 6. TABLA: DISPONIBILIDAD
CREATE TABLE IF NOT EXISTS public.disponibilidad (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finca_id UUID NOT NULL REFERENCES public.fincas(id) ON DELETE CASCADE,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    estado TEXT NOT NULL DEFAULT 'ocupado' CHECK (estado IN ('ocupado', 'libre')),
    personas INTEGER,
    notas TEXT, -- Nombre del cliente o notas internas
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT check_fechas CHECK (fecha_fin >= fecha_inicio)
);

CREATE INDEX IF NOT EXISTS idx_disponibilidad_finca_fechas 
    ON public.disponibilidad(finca_id, fecha_inicio, fecha_fin);

-- 7. POLÍTICAS DE SEGURIDAD (ROW LEVEL SECURITY - RLS)
-- Activar RLS en todas las tablas
ALTER TABLE public.fincas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.finca_imagenes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.finca_amenidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.finca_planes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.disponibilidad ENABLE ROW LEVEL SECURITY;

-- Lectura pública para fincas activas
CREATE POLICY "Lectura pública de fincas activas"
    ON public.fincas FOR SELECT
    TO anon, authenticated
    USING (activo = true);

-- Operaciones completas de fincas solo para usuarios autenticados (admin)
CREATE POLICY "Admin gestión total fincas"
    ON public.fincas FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- Lectura pública de imágenes
CREATE POLICY "Lectura pública de imágenes"
    ON public.finca_imagenes FOR SELECT
    TO anon, authenticated
    USING (true);

CREATE POLICY "Admin gestión total imágenes"
    ON public.finca_imagenes FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- Lectura pública de amenidades
CREATE POLICY "Lectura pública de amenidades"
    ON public.finca_amenidades FOR SELECT
    TO anon, authenticated
    USING (true);

CREATE POLICY "Admin gestión total amenidades"
    ON public.finca_amenidades FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- Lectura pública de planes
CREATE POLICY "Lectura pública de planes"
    ON public.finca_planes FOR SELECT
    TO anon, authenticated
    USING (true);

CREATE POLICY "Admin gestión total planes"
    ON public.finca_planes FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- Disponibilidad: Lectura pública de fechas y estado
CREATE POLICY "Lectura pública de disponibilidad"
    ON public.disponibilidad FOR SELECT
    TO anon, authenticated
    USING (true);

CREATE POLICY "Admin gestión total disponibilidad"
    ON public.disponibilidad FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- 8. CONFIGURACIÓN DEL BUCKET DE ALMACENAMIENTO (SUPABASE STORAGE)
-- Insertar el bucket finca-imagenes si no existe
INSERT INTO storage.buckets (id, name, public)
VALUES ('finca-imagenes', 'finca-imagenes', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Políticas de Storage
CREATE POLICY "Imágenes de fincas públicas"
    ON storage.objects FOR SELECT
    TO anon, authenticated
    USING (bucket_id = 'finca-imagenes');

CREATE POLICY "Subida de imágenes autenticada"
    ON storage.objects FOR INSERT
    TO authenticated
    WITH CHECK (bucket_id = 'finca-imagenes');

CREATE POLICY "Eliminación de imágenes autenticada"
    ON storage.objects FOR DELETE
    TO authenticated
    USING (bucket_id = 'finca-imagenes');
